name: Test Docker image

description: Test that a Docker image works as expected in the application context.

inputs:
  application-repository:
    required: true
    type: string
  application-repository-branch:
    required: false
    type: string
    default: main
  service:
    required: false
    type: string
    default: app
  image:
    required: true
    type: string
  image-tag:
    required: true
    type: string
  expected-user:
    required: true
    type: string
  application-protocol:
    required: false
    type: string
    default: http
  environment-overrides:
    required: false
    type: string

runs:
  using: "composite"
  steps:
    - name: Checkout
      uses: actions/checkout@v6
      with:
        repository: ${{ inputs.application-repository }}
        ref: ${{ inputs.application-repository-branch }}
        path: ${{ inputs.application-repository }}

    - name: Create environment file
      run: |
        cd ${{ inputs.application-repository }}
        touch .env
      shell: bash

    - name: Populate environment file
      if: ${{ inputs.environment-overrides != '' }}
      run: |
        cd ${{ inputs.application-repository }}
        echo "${{ inputs.environment-overrides }}" > .env
      shell: bash

    - name: Start application and wait for it to be healthy
      run: |
        cd ${{ inputs.application-repository }}
        yq '(.services.${{ inputs.service }}.build.args.IMAGE|="${{ inputs.image }}")' docker-compose.yml > tmp.$$.yml && mv tmp.$$.yml docker-compose.yml
        yq '(.services.${{ inputs.service }}.build.args.IMAGE_TAG|="${{ inputs.image-tag }}")' docker-compose.yml > tmp.$$.yml && mv tmp.$$.yml docker-compose.yml
        yq '(.services.${{ inputs.service }}.env_file|=".env")' docker-compose.yml > tmp.$$.yml && mv tmp.$$.yml docker-compose.yml
        cat docker-compose.yml
        docker compose up ${{ inputs.service }} --detach --wait || docker compose logs ${{ inputs.service }}
      shell: bash

    - name: Check user
      run: |
        cd ${{ inputs.application-repository }}
        docker compose exec ${{ inputs.service }} whoami
        # docker compose exec ${{ inputs.service }} whoami | grep "${{ inputs.expected-user }}"
      shell: bash
