name: Set up Wiz

inputs:
  wiz-client-id:
    required: true
    type: string
  wiz-client-secret:
    required: true
    type: string

runs:
  using: "composite"
  steps:
    - name: Download Wiz CLI
      run: |
        curl -Lo wizcli https://downloads.wiz.io/wizcli/latest/wizcli-linux-amd64

        # Import the public key
        curl -Lo public_key.asc https://downloads.wiz.io/wizcli/public_key.asc
        gpg --import public_key.asc
        # (OR) Ubuntu's Keyserver
        # gpg --keyserver keyserver.ubuntu.com --recv-keys CE4AE4BAD12EE02C

        # Download files to perform signature verification
        mkdir tmp
        curl -Lo tmp/wizcli-sha256 https://downloads.wiz.io/wizcli/latest/wizcli-linux-amd64-sha256
        curl -Lo tmp/wizcli-sha256.sig https://downloads.wiz.io/wizcli/latest/wizcli-linux-amd64-sha256.sig

        # Verify signature
        gpg --verify tmp/wizcli-sha256.sig tmp/wizcli-sha256

        # Verify SHA256
        echo "$(cat tmp/wizcli-sha256) wizcli" | sha256sum --check
        rm -fR tmp
        chmod +x wizcli
      shell: bash

    - name: Authenticate Wiz API
      run: ./wizcli auth --id ${{ inputs.wiz-client-id }} --secret ${{ inputs.wiz-client-secret }}
      shell: bash
