name: Test Docker image build

description: Build a Docker image and generate version tags based on the git ref.

inputs:
  image-name:
    required: true
    type: string
  dockerfile-path:
    required: true
    type: string
  base-image:
    required: false
    type: string

runs:
  using: "composite"
  steps:
    - name: Prepare image tag
      id: generate-tags
      run: |
        # Strip git ref prefix from version
        VERSION=$(echo "${{ github.ref }}" | sed -e 's,.*/\(.*\),\1,')
        # Strip "v" prefix from tag name and add the commit count as a build number
        [[ "${{ github.ref }}" == "refs/tags/"* ]] && VERSION=$(echo $VERSION | sed -e 's/^v//')
        VERSION_PART_MAJOR=$(echo "$VERSION" | awk -F'.' '{print $1}')
        VERSION_PART_MINOR=$(echo "$VERSION" | awk -F'.' '{print $2}')
        [ "$VERSION" == "main" ] && VERSION=preview
        echo "IMAGE_ID:           ${{ inputs.image-name }}"
        echo "VERSION:            $VERSION"
        echo "VERSION_PART_MAJOR: $VERSION_PART_MAJOR"
        echo "VERSION_PART_MINOR: $VERSION_PART_MINOR"
        echo "tag=$VERSION" >> "$GITHUB_OUTPUT"
        echo "major-version=$VERSION_PART_MAJOR" >> "$GITHUB_OUTPUT"
        echo "minor-version=$VERSION_PART_MINOR" >> "$GITHUB_OUTPUT"
      shell: bash

    - name: Build images
      uses: docker/build-push-action@v6
      with:
        context: ${{ inputs.dockerfile-path }}
        labels: |
          runnumber=${{ github.run_id }}
        build-args: |
          BASE_IMAGE=${{ inputs.base-image }}
          BASE_IMAGE_TAG=${{ steps.generate-tags.outputs.tag }}
          TNA_DOCKER_IMAGE_VERSION=${{ steps.generate-tags.outputs.tag }}
          TNA_DOCKER_IMAGE_SOURCE=${{ github.server_url	}}/${{ github.repository }}/blob/main/${{ inputs.dockerfile-path }}/Dockerfile
        push: false
        load: true
        tags: ${{ inputs.image-name }}:${{ steps.generate-tags.outputs.tag }}
        provenance: false

outputs:
  tag:
    description: "The generated tag"
    value: ${{ steps.generate-tags.outputs.tag }}
  major-version:
    value: ${{ steps.generate-tags.outputs.major-version }}
  minor-version:
    value: ${{ steps.generate-tags.outputs.minor-version }}
