name: Test Docker image build

description: Build a Docker image and generate version tags based on the git ref.

inputs:
  image-name:
    required: true
    type: string
  dockerfile-path:
    required: true
    type: string
  base-image:
    required: false
    type: string

runs:
  using: "composite"
  steps:
    - name: Create version tag
      id: version-tag
      uses: nationalarchives/ds-docker-actions/.github/actions/get-version-tag@main  # TODO: Could replace the "Prepare image tag" step below?

    - name: Test new image tag
      run: |
        VERSION=${STEPS_VERSION_TAG_OUTPUTS_VERSION_TAG}
        VERSION_PART_MAJOR=$(echo "$VERSION" | awk -F'.' '{print $1}')
        VERSION_PART_MINOR=$(echo "$VERSION" | awk -F'.' '{print $2}')
        echo "VERSION:            $VERSION"
        echo "VERSION_PART_MAJOR: $VERSION_PART_MAJOR"
        echo "VERSION_PART_MINOR: $VERSION_PART_MINOR"
      shell: bash
      env:
        STEPS_VERSION_TAG_OUTPUTS_VERSION_TAG: ${{ steps.version-tag.outputs.version-tag }}

    - name: Prepare image tag
      id: generate-tags
      run: |
        # Strip git ref prefix from version
        VERSION=$(echo "${GITHUB_REF}" | sed -e 's,.*/\(.*\),\1,')
        # Strip "v" prefix from tag name and add the commit count as a build number
        [[ "${GITHUB_REF}" == "refs/tags/"* ]] && VERSION=$(echo $VERSION | sed -e 's/^v//')
        VERSION_PART_MAJOR=$(echo "$VERSION" | awk -F'.' '{print $1}')
        VERSION_PART_MINOR=$(echo "$VERSION" | awk -F'.' '{print $2}')
        [ "$VERSION" == "main" ] && VERSION=preview
        echo "IMAGE_ID:           ${INPUTS_IMAGE_NAME}"
        echo "VERSION:            $VERSION"
        echo "VERSION_PART_MAJOR: $VERSION_PART_MAJOR"
        echo "VERSION_PART_MINOR: $VERSION_PART_MINOR"
        echo "tag=$VERSION" >> "$GITHUB_OUTPUT"
        echo "major-version=$VERSION_PART_MAJOR" >> "$GITHUB_OUTPUT"
        echo "minor-version=$VERSION_PART_MINOR" >> "$GITHUB_OUTPUT"
      shell: bash
      env:
        INPUTS_IMAGE_NAME: ${{ inputs.image-name }}

    - name: Build image
      run: |
        docker build --tag ${INPUTS_IMAGE_NAME}:${STEPS_GENERATE_TAGS_OUTPUTS_TAG} --build-arg "BUILD_VERSION=${STEPS_GENERATE_TAGS_OUTPUTS_TAG}" --build-arg "CONTAINER_IMAGE=${IMAGE_NAME}" --build-arg "BASE_IMAGE=${INPUTS_BASE_IMAGE}" --build-arg "BASE_IMAGE_TAG=${STEPS_GENERATE_TAGS_OUTPUTS_TAG}" --build-arg "TNA_DOCKER_IMAGE_VERSION=${STEPS_GENERATE_TAGS_OUTPUTS_TAG}" --build-arg "TNA_DOCKER_IMAGE_SOURCE=${{ github.server_url	}}/${{ github.repository }}/blob/main/${INPUTS_DOCKERFILE_PATH}/Dockerfile" --platform linux/amd64 --no-cache ${INPUTS_DOCKERFILE_PATH}
        docker inspect ${INPUTS_IMAGE_NAME}:${STEPS_GENERATE_TAGS_OUTPUTS_TAG}
        docker images --digests
      shell: bash
      env:
        INPUTS_IMAGE_NAME: ${{ inputs.image-name }}
        STEPS_GENERATE_TAGS_OUTPUTS_TAG: ${{ steps.generate-tags.outputs.tag }}
        INPUTS_BASE_IMAGE: ${{ inputs.base-image }}
        INPUTS_DOCKERFILE_PATH: ${{ inputs.dockerfile-path }}

outputs:
  tag:
    description: "The generated tag"
    value: ${{ steps.generate-tags.outputs.tag }}
  major-version:
    value: ${{ steps.generate-tags.outputs.major-version }}
  minor-version:
    value: ${{ steps.generate-tags.outputs.minor-version }}
