name: Push Docker image

inputs:
  image-name:
    required: true
    type: string
  image-tag:
    required: true
    type: string
  docker-context:
    required: true
    type: string
  base-image:
    required: false
    type: string
  user-image:
    required: false
    type: string
    default: appuser
  ignore-linting-rules:
    required: false
    type: string
  github-token:
    required: true
    type: string

runs:
  using: "composite"
  steps:
    # - uses: hadolint/hadolint-action@v3.1.0
    #   with:
    #     dockerfile: ${{ inputs.docker-context }}/Dockerfile
    #     ignore: SC1091,${{ inputs.ignore-linting-rules }}
    # - name: ShellCheck
    #   run: |
    #     cd ${{ inputs.docker-context }}
    #     [ -d "./bin" ] && shellcheck --external-sources --exclude=SC1091 ./bin/*
    #     shellcheck --external-sources --exclude=SC2148 ./Dockerfile
    #   shell: bash
    - name: Log in to registry
      run: echo "${{ inputs.github-token }}" | docker login ghcr.io -u $ --password-stdin
      shell: bash
    - name: Prepare image tag
      id: generate-tags
      run: |
        VERSION_MAJOR=$(echo "${{ inputs.image-tag }}" | awk -F'.' '{print $1}')
        VERSION_MINOR=$(echo "${{ inputs.image-tag }}" | awk -F'.' '{print $2}')
        echo "TAG=$VERSION" >> "$GITHUB_ENV"
        echo "MAJOR_VERSION=$VERSION_MAJOR" >> "$GITHUB_ENV"
        echo "MINOR_VERSION=$VERSION_MAJOR.$VERSION_MINOR" >> "$GITHUB_ENV"
      shell: bash
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    - name: Build and push images
      uses: docker/build-push-action@v6
      with:
        context: ${{ inputs.docker-context }}
        platforms: linux/amd64,linux/arm64
        labels: |
          runnumber=${{ github.run_id }}
        build-args: |
          BASE_IMAGE=${{ inputs.base-image }}
          BASE_IMAGE_TAG=${{ env.TAG }}
          TNA_DOCKER_IMAGE_VERSION=${{ env.TAG }}
          TNA_DOCKER_IMAGE_SOURCE=${{ github.server_url	}}/${{ github.repository }}/blob/main/${{ inputs.docker-context }}/Dockerfile
          USER_IMAGE=${{ inputs.user-image }}
        push: true
        tags: ${{ env.IMAGE_ID }}:${{ env.TAG }}
        provenance: false
    - name: List manifest
      run: docker buildx imagetools inspect ${{ env.IMAGE_ID }}:${{ env.TAG }}
      shell: bash
    - name: Tag major version
      if: startsWith(github.ref, 'refs/tags/')
      uses: docker/build-push-action@v6
      with:
        context: ${{ inputs.docker-context }}
        platforms: linux/amd64,linux/arm64
        labels: |
          runnumber=${{ github.run_id }}
        build-args: |
          BASE_IMAGE=${{ inputs.base-image }}
          BASE_IMAGE_TAG=${{ env.MAJOR_VERSION }}
          TNA_DOCKER_IMAGE_VERSION=${{ env.TAG }}
          TNA_DOCKER_IMAGE_SOURCE=${{ github.server_url	}}/${{ github.repository }}/blob/main/${{ inputs.docker-context }}/Dockerfile
          USER_IMAGE=${{ inputs.user-image }}
        push: true
        tags: ${{ env.IMAGE_ID }}:${{ env.MAJOR_VERSION }}
        provenance: false
    - name: Tag minor version
      if: startsWith(github.ref, 'refs/tags/')
      uses: docker/build-push-action@v6
      with:
        context: ${{ inputs.docker-context }}
        platforms: linux/amd64,linux/arm64
        labels: |
          runnumber=${{ github.run_id }}
        build-args: |
          BASE_IMAGE=${{ inputs.base-image }}
          BASE_IMAGE_TAG=${{ env.MINOR_VERSION }}
          TNA_DOCKER_IMAGE_VERSION=${{ env.TAG }}
          TNA_DOCKER_IMAGE_SOURCE=${{ github.server_url	}}/${{ github.repository }}/blob/main/${{ inputs.docker-context }}/Dockerfile
          USER_IMAGE=${{ inputs.user-image }}
        push: true
        tags: ${{ env.IMAGE_ID }}:${{ env.MINOR_VERSION }}
        provenance: false
    - name: Tag latest
      if: startsWith(github.ref, 'refs/tags/')
      uses: docker/build-push-action@v6
      with:
        context: ${{ inputs.docker-context }}
        platforms: linux/amd64,linux/arm64
        labels: |
          runnumber=${{ github.run_id }}
        build-args: |
          BASE_IMAGE=${{ inputs.base-image }}
          BASE_IMAGE_TAG=latest
          TNA_DOCKER_IMAGE_VERSION=${{ env.TAG }}
          TNA_DOCKER_IMAGE_SOURCE=${{ github.server_url	}}/${{ github.repository }}/blob/main/${{ inputs.docker-context }}/Dockerfile
          USER_IMAGE=${{ inputs.user-image }}
        push: true
        tags: ${{ env.IMAGE_ID }}:latest
        provenance: false
    - name: Scan for vulnerabilities
      uses: aquasecurity/trivy-action@0.28.0
      with:
        image-ref: ${{ env.IMAGE_ID }}:${{ env.TAG }}
        format: "sarif"
        output: "trivy-results.sarif"
        ignore-unfixed: true
    - name: Upload Trivy scan results to GitHub Security tab
      uses: github/codeql-action/upload-sarif@v3
      with:
        sarif_file: "trivy-results.sarif"
