name: Build and push Docker images

description: Build and push Docker images to GitHub Container Registry with appropriate tags.

inputs:
  image-id:
    required: true
    type: string
  image-tag:
    required: true
    type: string
  major-version:
    required: true
    type: string
  minor-version:
    required: true
    type: string
  dockerfile-path:
    required: true
    type: string
  base-image:
    required: false
    type: string
  user-image:
    required: false
    type: string
    default: app
  github-token:
    required: true
    type: string

runs:
  using: "composite"
  steps:
    - name: Login to GitHub Container Registry
      uses: docker/login-action@4907a6ddec9925e35a0a9e82d7399ccc52663121 # v4.1.0
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ inputs.github-token }}

    - name: Set up QEMU
      uses: docker/setup-qemu-action@ce360397dd3f832beb865e1373c09c0e9f86d70a # v4.0.0

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@4d04d5d9486b7bd6fa91e7baf45bbb4f8b9deedd # v4.0.0

    - name: Build and push image
      uses: docker/build-push-action@bcafcacb16a39f128d818304e6c9c0c18556b85f # v7.1.0
      with:
        context: ${{ inputs.dockerfile-path }}
        platforms: linux/amd64,linux/arm64
        labels: |
          uk.gov.nationalarchives.runnumber=${{ github.run_id }}
        build-args: |
          BASE_IMAGE=${{ inputs.base-image }}
          BASE_IMAGE_TAG=${{ inputs.image-tag }}
          TNA_DOCKER_IMAGE_VERSION=${{ inputs.image-tag }}
          TNA_DOCKER_IMAGE_SOURCE=${{ github.server_url	}}/${{ github.repository }}/blob/main/${{ inputs.dockerfile-path }}/Dockerfile
        push: true
        tags: ${{ inputs.image-id }}:${{ inputs.image-tag }}
        provenance: false

    - name: List manifest
      run: docker buildx imagetools inspect ${{ inputs.image-id }}:${{ inputs.image-tag }}
      shell: bash

    - name: Build and push versioned and latest image tags
      if: startsWith(github.ref, 'refs/tags/')
      uses: docker/build-push-action@bcafcacb16a39f128d818304e6c9c0c18556b85f # v7.1.0
      with:
        context: ${{ inputs.dockerfile-path }}
        platforms: linux/amd64,linux/arm64
        labels: |
          uk.gov.nationalarchives.runnumber=${{ github.run_id }}
        build-args: |
          BASE_IMAGE=${{ inputs.base-image }}
          BASE_IMAGE_TAG=${{ inputs.image-tag }}
          TNA_DOCKER_IMAGE_VERSION=${{ inputs.image-tag }}
          TNA_DOCKER_IMAGE_SOURCE=${{ github.server_url	}}/${{ github.repository }}/blob/main/${{ inputs.dockerfile-path }}/Dockerfile
        push: true
        tags: ${{ inputs.image-id }}:${{ inputs.major-version }},${{ inputs.image-id }}:${{ inputs.major-version }}.${{ inputs.minor-version }},${{ inputs.image-id }}:latest
        provenance: false
