name: Lint Dockerfile

inputs:
  dockerfile-location:
    required: true
    type: string
  ignore-linting-rules:
    required: false
    type: string
  wiz-project-id:
    required: true
    type: string

runs:
  using: "composite"
  steps:
    - uses: hadolint/hadolint-action@v3.1.0
      with:
        dockerfile: ${{ inputs.dockerfile-location }}/Dockerfile
        ignore: ${{ inputs.ignore-linting-rules }}

    - name: ShellCheck
      run: |
        cd ${{ inputs.dockerfile-location }}
        [ -d "./bin" ] && shellcheck --external-sources --exclude=SC1091 ./bin/*
        shellcheck --external-sources --exclude=SC2148 ./Dockerfile
      shell: bash

    - name: Scan DockerFile with Wiz
      if: ${{ env.DISABLE_WIZ != 'true' }}
      run: ./wizcli iac scan --path ${{ inputs.dockerfile-location }} --types Dockerfile --tag ${{ inputs.dockerfile-location }} --project ${{ inputs.wiz-project-id }} --ignore-comments
      shell: bash
