name: Lint Dockerfile

inputs:
  docker-context:
    required: true
    type: string
  ignore-linting-rules:
    required: false
    type: string

runs:
  using: "composite"
  steps:
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    - uses: hadolint/hadolint-action@v3.1.0
      with:
        dockerfile: ${{ inputs.docker-context }}/Dockerfile
        ignore: SC1091,${{ inputs.ignore-linting-rules }}
    - name: ShellCheck
      run: |
        cd ${{ inputs.docker-context }}
        [ -d "./bin" ] && shellcheck --external-sources --exclude=SC1091 ./bin/*
        shellcheck --external-sources --exclude=SC2148 ./Dockerfile
      shell: bash
