ARG BASE_IMAGE_TAG=latest
FROM ghcr.io/nationalarchives/tna-python-django:"$BASE_IMAGE_TAG"

# ==========================================
# Switch to the root user which allows us to
# have full access to the file system
# ==========================================
USER root
