name: Scan Docker image

inputs:
  image-id:
    required: true
    type: string
  image-tag:
    required: true
    type: string

runs:
  using: "composite"
  steps:
    - name: Scan for vulnerabilities
      uses: aquasecurity/trivy-action@0.28.0
      with:
        image-ref: ${{ inputs.image-id }}:${{ inputs.image-tag }}
        format: "sarif"
        output: "trivy-results.sarif"
        ignore-unfixed: true

    - name: Upload Trivy scan results to GitHub Security tab
      uses: github/codeql-action/upload-sarif@v3
      with:
        sarif_file: "trivy-results.sarif"
