name: Lint

on:
  workflow_call:
    inputs:
      image-name:
        required: true
        type: string
      docker-context:
        required: true
        type: string
      dockerfile:
        required: true
        type: string

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - uses: hadolint/hadolint-action@v3.1.0
      with:
        dockerfile: ${{ inputs.docker-context }}/${{ inputs.dockerfile }}
        ignore: DL3007
    - name: Shellcheck
      run: |
        cd docker/${{ inputs.image-name }}
        shellcheck --external-sources --exclude=SC1091 ./bin/*
        shellcheck --external-sources --exclude=SC2148 ./Dockerfile
