name: Build and publish

on:
  release:
    types:
      - published
  push:
    branches:
      - main
      - feature/**

concurrency:
  group: ${{ github.ref }}-publish
  cancel-in-progress: true

jobs:
  python:
    name: Python
    uses: ./.github/workflows/_docker-build-deploy.yml
    with:
      image-name: tna-python
      docker-context: docker/tna-python
      dockerfile: Dockerfile
      publish: true
      ignore-linting-rules: DL3002

  python-root:
    name: Python (root)
    uses: ./.github/workflows/_docker-build-deploy.yml
    with:
      image-name: tna-python-root
      docker-context: docker/tna-python
      user-image: root
      dockerfile: Dockerfile
      publish: true
      ignore-linting-rules: DL3002

  python-django:
    name: Python Django
    needs: python
    uses: ./.github/workflows/_docker-build-deploy.yml
    with:
      image-name: tna-python-django
      docker-context: docker/tna-python-django
      dockerfile: Dockerfile
      publish: true

  python-django-root:
    name: Python Django (root)
    needs: python-root
    uses: ./.github/workflows/_docker-build-deploy.yml
    with:
      image-name: tna-python-django-root
      docker-context: docker/tna-python-django
      dockerfile: Dockerfile
      publish: true
      ignore-linting-rules: DL3002
