name: CI

on:
  push:       # FOR TESTING
    branches: # FOR TESTING
      - main  # FOR TESTING
  release:
    types:
      - published

jobs:
  python:
    name: Python
    uses: ./.github/workflows/docker-build-deploy.yml
    with:
      image-name: tna-python
      docker-context: docker/tna-python
      dockerfile: Dockerfile

  python-django:
    name: Python Django
    needs: python
    uses: ./.github/workflows/docker-build-deploy.yml
    with:
      image-name: tna-python-django
      docker-context: docker/tna-python-django
      dockerfile: Dockerfile

  python-poetry:
    name: Python Poetry
    needs: python
    uses: ./.github/workflows/docker-build-deploy.yml
    with:
      image-name: tna-python-poetry
      docker-context: docker/tna-python-poetry
      dockerfile: Dockerfile
