name: CI tests

on:
  push:
    branches:
      - '!main'
      - '!feature/**'

concurrency:
  group: ${{ github.ref }}-test
  cancel-in-progress: true

jobs:
  python:
    name: Python
    uses: ./.github/workflows/_docker-build-deploy.yml
    with:
      image-name: tna-python
      docker-context: docker/tna-python
      dockerfile: Dockerfile
      publish: false
      ignore-linting-rules: DL3002,DL3006

  python-root:
    name: Python (root)
    uses: ./.github/workflows/_docker-build-deploy.yml
    with:
      image-name: tna-python-root
      docker-context: docker/tna-python
      user-image: root
      dockerfile: Dockerfile
      publish: false
      ignore-linting-rules: DL3002,DL3006

  python-django:
    name: Python Django
    needs: python
    uses: ./.github/workflows/_docker-build-deploy.yml
    with:
      image-name: tna-python-django
      base-image: ghcr.io/nationalarchives/tna-python
      docker-context: docker/tna-python-django
      dockerfile: Dockerfile
      publish: false

  python-django-root:
    name: Python Django (root)
    needs: python-root
    uses: ./.github/workflows/_docker-build-deploy.yml
    with:
      image-name: tna-python-django-root
      base-image: ghcr.io/nationalarchives/tna-python-root
      docker-context: docker/tna-python-django
      dockerfile: Dockerfile
      publish: false
      ignore-linting-rules: DL3002
