name: CI tests

on:
  push:
    branches:
      - main
      - '!feature/**'

concurrency:
  group: ${{ github.ref }}-test
  cancel-in-progress: true

jobs:
  python:
    name: Python
    uses: ./.github/workflows/_docker-build-deploy.yml
    with:
      image-name: tna-python
      docker-context: docker/tna-python
      dockerfile: Dockerfile
      publish: false

  python-django:
    name: Python Django
    needs: python
    uses: ./.github/workflows/_docker-build-deploy.yml
    with:
      image-name: tna-python-django
      docker-context: docker/tna-python-django
      dockerfile: Dockerfile
      publish: false
