name: CI tests

on:
  push:
    branches:
      - '!main'
      - '!feature/**'

concurrency:
  group: ${{ github.ref }}-test
  cancel-in-progress: true

jobs:
  python:
    name: Python
    uses: ./.github/workflows/_docker-build-deploy.yml
    with:
      image-name: tna-python
      docker-context: docker/tna-python
      dockerfile: Dockerfile
      publish: false

  python-root:
    name: Python (root)
    needs: python
    uses: ./.github/workflows/_docker-build-deploy.yml
    with:
      image-name: tna-python-root
      docker-context: docker/tna-python-root
      dockerfile: Dockerfile
      publish: false
      ignore-linting-rules: DL3002

  python-flask:
    name: Python Flask
    needs: python
    uses: ./.github/workflows/_docker-build-deploy.yml
    with:
      image-name: tna-python-flask
      docker-context: docker/tna-python-flask
      dockerfile: Dockerfile
      publish: false

  python-django:
    name: Python Django
    needs: python
    uses: ./.github/workflows/_docker-build-deploy.yml
    with:
      image-name: tna-python-django
      docker-context: docker/tna-python-django
      dockerfile: Dockerfile
      publish: false

  python-django-root:
    name: Python Django (root)
    needs: python-django
    uses: ./.github/workflows/_docker-build-deploy.yml
    with:
      image-name: tna-python-django-root
      docker-context: docker/tna-python-django-root
      dockerfile: Dockerfile
      publish: false
      ignore-linting-rules: DL3002
