name: Test

on:
  push:
    branches: # TODO: Remove branches filter once released
      main    # TODO: Remove branches filter once released

jobs:
  python:
    name: Python
    uses: ./.github/workflows/docker-build-deploy.yml
    with:
      image-name: tna-python
      docker-context: docker/tna-python
      dockerfile: Dockerfile
      publish: true # TODO: Disable once released

  # python-django:
  #   name: Python Django
  #   needs: python
  #   uses: ./.github/workflows/docker-build-deploy.yml
  #   with:
  #     image-name: tna-python-django
  #     docker-context: docker/tna-python-django
  #     dockerfile: Dockerfile
  #     publish: false
